name: Append New Quotes

on:
  push:
    paths:
      - 'incoming/*.json'

jobs:
  append:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Append new quotes
        run: |
          echo "Reading quotes..."
          cat quotes.json > all_quotes.json
          for file in incoming/quote-*.json; do
            if [ -s "$file" ]; then
              echo "Processing $file"
              node -e "
                const fs = require('fs');
                const main = JSON.parse(fs.readFileSync('all_quotes.json', 'utf-8'));
                const incoming = JSON.parse(fs.readFileSync('$file', 'utf-8'));
                main.push(incoming);
                fs.writeFileSync('all_quotes.json', JSON.stringify(main, null, 2));
              "
              rm "$file"
            fi
          done
          mv all_quotes.json quotes.json

      - name: Commit and push updated quotes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Append new quotes to quotes.json"
          file_pattern: quotes.json
